### ISSUE TITLE
CPU usage is always 100%

### ISSUE THREAD

**Issue by zenithfurfid** [cslrfid/CS108-iOS-Swift-App#6]
![Screen Shot 2022-04-07 at 8 45 03 AM](https://user-images.githubusercontent.com/99494633/162209472-8faadc06-7cc4-48fa-b066-dcda683b4a85.png)

While I run this project, CPU usage is about 100% once I connect to a handheld.
Could you investigate and fix it?

**Comment by ksclam** [comment]
On the reader library, there is a selector running on a background thread for decoding the data packets being received.  It runs in loop and occupies CPU time even if there is no packets in the queue.  Please refer to the fix on the new branch below that addressed this issue.  The thread will sleep and release CPU time when there is not packets in the queue.  

The fix will be merged back to the main on the upcoming release.

https://github.com/cslrfid/CS108-iOS-Swift-App/blob/f11ecc63e51a8bb7fae49e80121b88f00ff76469/CS108iOSClient/CSLReader/CSLBleReader.m#L2989

**Comment by zenithfurfid** [comment]
Thank you very much.
It works well for me.
