### ISSUE TITLE
Antenna Power issue

### ISSUE THREAD

**Issue by zenithfurfid** [cslrfid/CS108-iOS-Swift-App#7]
![setings](https://user-images.githubusercontent.com/99494633/163090905-637afd9f-e592-4e14-b81b-06113434d11f.png)

As you can see I set the power as 0.
But I can still detect tags on the Inventory page.
It looks like it doesn't work setting the power.

**Comment by ksclam** [comment]
The unit of measure is decibel-milliwatts (dBm), where 300 means 30.0 dBm.  0 does not really mean 0 in real power and it actually translate to 1 mW.  Therefore, you will be still seeing tag reads when power is 0 but at a much lower read range.

**Comment by zenithfurfid** [comment]
Got it.
Thanks so much for your kind explanation.
